package gullsview;

import java.util.*;


public class Resources_cs extends ListResourceBundle {
	private static final Object[][] CONTENTS = new Object[][]{
		{"error", "Chyba"},
		{"error-before", "Nastala následující chyba"},
		{"error-after", "Nyní prosím ukončete aplikaci"},
		{"error-not-int", "Zadejte prosím celočíselnou hodnotu"},
		{"error-not-double", "Zadejte prosím číslo"},
		{"error-not-boolean", "Zadejte prosím ano nebo ne"},
		{"error-incorrect-path", "Chybná cesta k adresáři"},
		{"error-not-exist", "Zadaný adresář neexistuje"},
		{"error-not-directory", "Zadaná cesta neodpovídá adresáři"},
		{"error-empty", "Prázdný vstup není povolen"},
		{"error-not-coord", "Zadaný text nelze převést na souřadnici"},
		{"error-file-not-exist", "Zadaný soubor neexistuje"},
		{"error-not-file", "Zadaná cesta neodpovídá souboru"},
		{"yes", "ano"},
		{"no", "ne"},
		{"title", "Gull's View - Packer"},
		{"accept", "Potvrdit"},
		{"question", "Dotaz"},
		{"answer", "Odpověď"},
		{"enable-fc", "Zapnout podporu JSR 075 - File Connection? (na zařízeních bez tohoto rozšíření API však aplikace nebude fungovat)"},
		{"enable-bt", "Zapnout podporu JSR 082 - Bluetooth API? (samotná podpora Bluetooth v zařízení nestačí, na zařízeních bez tohoto rozšíření API však aplikace nebude fungovat)"},
		{"enable-lapi", "Zapnout podporu JSR 179 - Location API? (na zařízeních bez tohoto rozšíření API však aplikace nebude fungovat)"},
		{"enable-m3g", "Zapnout podporu JSR 184 - Mobile 3D Graphics? (na zařízeních bez tohoto rozšíření API však aplikace nebude fungovat)"},
		{"enable-bts", "Zapnout podporu lokalizace pomoci BTS? (funguje pouze na některých telefonech SonyEricsson a Nokia)"},
		{"output-path", "Zadejte cestu k adresáři pro uložení výsledného midlet suite (mobilní aplikace - JAR+JAD)"},
		{"output-name", "Zadejte název výsledného midlet suite (mobilní aplikace - JAR+JAD)"},
		{"start", "Začínám generovat midlet suite"},
		{"finish", "Hotovo"},
		{"accept-to-close", "Pro ukončení aplikace potvrďte vstup"},
		{"world", "Svět"},
		{"map-count", "Zadejte počet map"},
		{"map-name", "Identifikátor mapy (bez mezer, diakritiky a speciálních znaků)"},
		{"map-title", "Titulek mapy"},
		{"map-vendor", "Vaše jméno a příjmení"},
		{"map-scale", "Číselné označení měřítka mapy (větší číslo = větší detail)"},
		{"map-segment", "Rozměr mapové dlaždice (čtvercového obrázku) v pixelech"},
		{"map-xcount", "Počet mapových dlaždic ve vodorovném směru"},
		{"map-ycount", "Počet mapových dlaždic ve svislém směru"},
		{"map-mercator", "Jsou vstupní data vytvořena v projekci jménem Mercator? (Mercator používá např. projekt www.openstreetmap.org nebo maps.google.com)"},
		{"map-segoffsetx", "Zadejte offset levé horní dlaždice na X-ové ose (tj. globální x-ový index té dlaždice mapy, která je interně uložena v souboru jménem 0_0)"},
		{"map-segoffsety", "Zadejte offset levé horní dlaždice na Y-ové ose (tj. globální y-ový index té dlaždice mapy, která je interně uložena v souboru jménem 0_0)"},
		{"map-lt-lat", "Souřadnice levého horního rohu mapy - zemská šířka (latitude)"},
		{"map-lt-lon", "Souřadnice levého horního rohu mapy - zemská délka (longitude)"},
		{"map-rt-lat", "Souřadnice pravého horního rohu mapy - zemská šířka (latitude)"},
		{"map-rt-lon", "Souřadnice pravého horního rohu mapy - zemská délka (longitude)"},
		{"map-lb-lat", "Souřadnice levého dolního rohu mapy - zemská šířka (latitude)"},
		{"map-lb-lon", "Souřadnice levého dolního rohu mapy - zemská délka (longitude)"},
		{"map-lat", "Výchozí souřadnice mapy - zemská šířka (latitude)"},
		{"map-lon", "Výchozí souřadnice mapy - zemská délka (longitude)"},
		{"map-data-dir", "Zadejte adresář obsahující mapové dlaždice"},
		{"map-data-format", "Formát názvů souborů s mapovými dlaždicemi - za {0} se dosadí vodorovný index dlaždice, za {1} svislý. Indexuje se od nuly."},
		{"map-data-included", "Mají být mapové dlaždice (obrázky) vloženy do výsledného aplikačního JAR archivu?"},
		{"map-no-params", "Parametry mapy číslo"},
		{"processing-manifest", "Zpracovávám Manifest"},
		{"processing-entry", "Zpracovávám JAR položku"},
		{"writing-resource-entry", "Zapisuji JAR položku z vlastních zdrojů"},
		{"adding-segment-file-to-archive", "Přidávám do archivu dlaždici"},
		{"adding-segment-file-to-dir", "Vytvářím soubor pro uložení na paměťovou kartu zařízení"},
		{"writing-output-start", "Vytvářím midlet suite"},
		{"writing-output-finish", "Midlet suite vytvořen"},
		{"copy-data-along", "POZOR!!! Před nasazením aplikace nejprve do mobilního zařízení nakopírujte vytvořený adresář s mapovými daty!"},
		{"usage-0", "Použití:"},
		{"usage-1", "java -jar GullsViewPacker.jar [-stdio] [-properties FILE] [-swing]"},
		{"usage-2", "kde jednotlivé volby znamenají toto:"},
		{"usage-3", "-stdio - spustí aplikaci v textovém režimu (z textové konzole)"},
		{"usage-4", "-properties FILE - spustí aplikaci v dávkovém režimu - odpovědi na všechny dotazy čerpá ze souboru FILE ve formátu Java Properties"},
		{"usage-5", "-swing - spustí aplikaci v grafickém režimu (výchozí volba)"},
		{"overview-0", "Tato aplikace Vás v několika krocích provede procesem vytvoření mapové aplikace pro mobilní telefon."},
		{"overview-1", "Nejdříve si připravte mapová data ve formě čtvercových obrázků - dlaždic, z nichž bude celková mapa seskládána."},
		{"overview-2", "Soubory s jednotlivými dlaždicemi si pojmenujte tak, aby název obsahoval číselný index řádku a sloupce této dlaždice (např. 10_12.png, 11_1.png, atd.)."},
		{"overview-3", "Levá horní dlaždice má index 0:0, soubor se tedy bude jmenovat např. 0_0.png"},
		{"overview-4", "Dále je dobré vědět jakým způsobem se mají přepočítávat mapové souřadnice na skutečné zemské souřadnice (zemská šířka, zemská délka)"},
		{"overview-5", "Tato aplikace umožňuje počítání souřadnic dvěma způsoby - systémem Mercator a bilineární transformací:"},
		{"overview-6", "1) Mercator - je projekcí geoidu na váleci s pyramidovým dělením dlaždic na 4 poddlaždice s vyšším rozlišením, používá jej např. projekt www.openstreetmap.org nebo maps.google.com."},
		{"overview-7", "Pokud máte dlaždice v této projekci, stačí Vám znát tyto tři informace: X-ovou a Y-ovou souřadnici levé horní dlaždice a číslo úrovně přiblížení (0 znamená celá země v jediné dlaždici, 1 znamená celá země ve 4 dlaždicích, 2 - v 16 dlaždicích, atd."},
		{"overview-8", "Tyto tři hodnoty jsou většinou součástí URL adresy pomocí níž byla konkrétní dlaždice stažena z dlaždicového serveru."},
		{"overview-9", "2) Bilineární transformace - v tomto případě se souřadnice interpoluje ze zadaných zemských souřadnic tří rohů mapy."},
		{"overview-10", "Dále je nutné znát parametry mobilního zařízení, pro které mapovou aplikaci vytváříte."},
		{"overview-11", "Jde především o podporu jednotlivých rozšíření API - např. jestli má Java aplikace přístup k souborovému systému, k Bluetooth a podobně."},
		{"overview-12", "Pokud jste si jisti, že Vaše zařízení obsahuje podporu JSR-75-FileConnection, je možné dlaždice NEvložit do JAR archivu mobilní aplikace, ale pouze je umístit do adresáře na paměťové kartě zařízení a nechat mobilní aplikaci tyto data postupně číst pomoci JSR-75 API."},
		{"overview-13", "Pozor - někteří výrobci mobilních zařízení uživateli neumožní jednorázově povolit přístup Java aplikaci k paměťové kartě (souborovému systému) a při načtení každé další dlaždice uživatele obtěžují kontrolními otázkami."},
		{"overview-14", "Pokud tedy máte připraveny všechny mapové dlaždice a informace k počítání souřadnic, můžete odpovídat na jednotlivé otázky tohoto průvodce."},
		{"overview-15", "Po jeho dokončení bude ve zvoleném adresáři vytvořena dvojice souborů s příponami JAD a JAR které je možné obvyklým způsobem nahrát do mobilního zařízení s podporou Javy."},
		{"", ""},
	};
	
	public Object[][] getContents(){
		return CONTENTS;
	}
}


