package gullsview;

import java.util.*;


public class Resources extends ListResourceBundle {
	private static final Object[][] CONTENTS = new Object[][]{
		{"error", "Error"},
		{"error-before", "Following error occured"},
		{"error-after", "Please exit application now"},
		{"error-not-int", "Insert integer value please"},
		{"error-not-double", "Insert number please"},
		{"error-not-boolean", "Insert yes or no please"},
		{"error-incorrect-path", "Incorrect path to directory"},
		{"error-not-exist", "Directory does not exist"},
		{"error-not-directory", "Path is not a directory"},
		{"error-empty", "Empty input is not allowed"},
		{"error-not-coord", "Inserted text cannot be parsed as coordinate"},
		{"error-file-not-exist", "File does not exsist"},
		{"error-not-file", "Path is not a file"},
		{"yes", "yes"},
		{"no", "no"},
		{"title", "Gull's View - Packer"},
		{"accept", "Accept"},
		{"question", "Question"},
		{"answer", "Answer"},
		{"enable-fc", "Enable support of JSR 075 - File Connection? (on devices without this API extension application won't work)"},
		{"enable-bt", "Enable support of JSR 082 - Bluetooth API? (on devices without this API extension application won't work)"},
		{"enable-lapi", "Enable support of JSR 179 - Location API? (on devices without this API extension application won't work)"},
		{"enable-m3g", "Enable support of JSR 184 - Mobile 3D Graphics? (on devices without this API extension application won't work)"},
		{"enable-bts", "Enable support of localisation using BTS? (only works on certain SonyEricsson and Nokia devices)"},
		{"output-path", "Insert directory path for saving generated midlet suite (mobile application - JAR+JAD)"},
		{"output-name", "Insert name of generated midlet suite (mobile application - JAR+JAD)"},
		{"start", "Midlet suite generation started"},
		{"finish", "Finished"},
		{"accept-to-close", "Enter empty input to exit this application"},
		{"world", "World"},
		{"map-count", "Insert map count"},
		{"map-name", "Map identifier (no spaces or special characters)"},
		{"map-title", "Map title"},
		{"map-vendor", "Your name and surname"},
		{"map-scale", "Integer value of map zoom (greater number = higher detail)"},
		{"map-segment", "Size (width = height) of map tile (square map image) in pixels"},
		{"map-xcount", "Number of map tiles in horizontal axis"},
		{"map-ycount", "Number of map tiles in vertical axis"},
		{"map-mercator", "Are mapping data created in Mercator projection? (Mercator is used by eg. project www.openstreetmap.org or maps.google.com)"},
		{"map-segoffsetx", "Insert offset of left top tile at X axis (that is global x-index of map tile internally saved in a file named 0_0)"},
		{"map-segoffsety", "Insert offset of left top tile at Y axis (that is global y-index of map tile internally saved in a file named 0_0)"},
		{"map-lt-lat", "Coordinate of left top map corner - latitude"},
		{"map-lt-lon", "Coordinate of left top map corner - longitude"},
		{"map-rt-lat", "Coordinate of right top map corner - latitude"},
		{"map-rt-lon", "Coordinate of right top map corner - longitude"},
		{"map-lb-lat", "Coordinate of left bottom map corner - latitude"},
		{"map-lb-lon", "Coordinate of left bottom map corner - longitude"},
		{"map-lat", "Default map coordinate - latitude"},
		{"map-lon", "Default map coordinate - longitude"},
		{"map-data-dir", "Insert path to directory with map tiles"},
		{"map-data-format", "Map tile file name format - {0} is substitued by horizontal tile index, {1} is substitued by vertical index. Indices goes from zero."},
		{"map-data-included", "Should be map tiles (images) included into generated mobile JAR archive?"},
		{"map-no-params", "Parameters of map No."},
		{"processing-manifest", "Processing Manifest"},
		{"processing-entry", "Processing JAR entry"},
		{"writing-resource-entry", "Writing JAR entry from internal resources"},
		{"adding-segment-file-to-archive", "Adding tile into archive"},
		{"adding-segment-file-to-dir", "Creating file for moving to device memory card"},
		{"writing-output-start", "Creating midlet suite"},
		{"writing-output-finish", "Midlet suite successfully created"},
		{"copy-data-along", "ATTENTION!!! Copy created directory with map data (ending with suffix _DATA) into device memory card before mobile application deployment!"},
		{"usage-0", "Usage:"},
		{"usage-1", "java -jar GullsViewPacker.jar [-stdio] [-properties FILE] [-swing]"},
		{"usage-2", "where options means:"},
		{"usage-3", "-stdio - runs application in text mode (from text console)"},
		{"usage-4", "-properties FILE - runs application in batch mode - answers to all questions are read from FILE in Java Properties format"},
		{"usage-5", "-swing - runs application in graphic mode (default)"},
		{"overview-0", "Tato aplikace Vás v několika krocích provede procesem vytvoření mapové aplikace pro mobilní telefon."},
		{"overview-1", "Nejdříve si připravte mapová data ve formě čtvercových obrázků - dlaždic, z nichž bude celková mapa seskládána."},
		{"overview-2", "Soubory s jednotlivými dlaždicemi si pojmenujte tak, aby název obsahoval číselný index řádku a sloupce této dlaždice (např. 10_12.png, 11_1.png, atd.)."},
		{"overview-3", "Levá horní dlaždice má index 0:0, soubor se tedy bude jmenovat např. 0_0.png"},
		{"overview-4", "Dále je dobré vědět jakým způsobem se mají přepočítávat mapové souřadnice na skutečné zemské souřadnice (zemská šířka, zemská délka)"},
		{"overview-5", "Tato aplikace umožňuje počítání souřadnic dvěma způsoby - systémem Mercator a bilineární transformací:"},
		{"overview-6", "1) Mercator - je projekcí geoidu na váleci s pyramidovým dělením dlaždic na 4 poddlaždice s vyšším rozlišením, používá jej např. projekt www.openstreetmap.org nebo maps.google.com."},
		{"overview-7", "Pokud máte dlaždice v této projekci, stačí Vám znát tyto tři informace: X-ovou a Y-ovou souřadnici levé horní dlaždice a číslo úrovně přiblížení (0 znamená celá země v jediné dlaždici, 1 znamená celá země ve 4 dlaždicích, 2 - v 16 dlaždicích, atd."},
		{"overview-8", "Tyto tři hodnoty jsou většinou součástí URL adresy pomocí níž byla konkrétní dlaždice stažena z dlaždicového serveru."},
		{"overview-9", "2) Bilineární transformace - v tomto případě se souřadnice interpoluje ze zadaných zemských souřadnic tří rohů mapy."},
		{"overview-10", "Dále je nutné znát parametry mobilního zařízení, pro které mapovou aplikaci vytváříte."},
		{"overview-11", "Jde především o podporu jednotlivých rozšíření API - např. jestli má Java aplikace přístup k souborovému systému, k Bluetooth a podobně."},
		{"overview-12", "Pokud jste si jisti, že Vaše zařízení obsahuje podporu JSR-75-FileConnection, je možné dlaždice NEvložit do JAR archivu mobilní aplikace, ale pouze je umístit do adresáře na paměťové kartě zařízení a nechat mobilní aplikaci tyto data postupně číst pomoci JSR-75 API."},
		{"overview-13", "Pozor - někteří výrobci mobilních zařízení uživateli neumožní jednorázově povolit přístup Java aplikaci k paměťové kartě (souborovému systému) a při načtení každé další dlaždice uživatele obtěžují kontrolními otázkami."},
		{"overview-14", "Pokud tedy máte připraveny všechny mapové dlaždice a informace k počítání souřadnic, můžete odpovídat na jednotlivé otázky tohoto průvodce."},
		{"overview-15", "Po jeho dokončení bude ve zvoleném adresáři vytvořena dvojice souborů s příponami JAD a JAR které je možné obvyklým způsobem nahrát do mobilního zařízení s podporou Javy."},
		{"", ""},
	};
	
	public Object[][] getContents(){
		return CONTENTS;
	}
}


